# Generated by Django 4.2.4 on 2023-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauthtoken",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
