# Generated by Django 4.2.6 on 2023-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_userauthtoken_expired"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/ideas"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="files/products"),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
