# Generated by Django 4.2.6 on 2023-11-20 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0005_idearatings_ideacomments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ideacomments",
            options={
                "ordering": ("-date_time", "idea"),
                "verbose_name": "Комментарий к посту",
                "verbose_name_plural": "Комментарии к постам",
            },
        ),
        migrations.AlterModelOptions(
            name="idearatings",
            options={
                "ordering": ("-idea", "author"),
                "verbose_name": "Рейтинг к новости",
                "verbose_name_plural": "Рейтинги к новостям",
            },
        ),
        migrations.RenameField(
            model_name="ideacomments",
            old_name="post",
            new_name="idea",
        ),
        migrations.RenameField(
            model_name="idearatings",
            old_name="post",
            new_name="idea",
        ),
    ]
