# Generated by Django 4.2.4 on 2023-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_app",
            "0006_alter_ideacomments_options_alter_idearatings_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("summary", models.TextField()),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
                ("education", models.TextField()),
            ],
        ),
    ]
