# Generated by Django 4.2.6 on 2023-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0008_room_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
