# Generated by Django 4.2.4 on 2023-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0010_remove_resume_email_remove_resume_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="post",
            field=models.CharField(default="", max_length=100),
        ),
    ]
