# Generated by Django 4.2.4 on 2023-12-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_app", "0011_resume_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
