# Generated by Django 4.2.4 on 2023-12-06 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_app", "0012_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/resumes"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
