# Generated by Django 4.2.4 on 2023-12-06 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0013_resume_image_alter_resume_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAuthToken",
        ),
    ]
